export const packetNames = [
  // 그거 아시나요 이 프로젝트.. gamePacket만 쓴다는 사실
  // 'Position',
  // 'CharacterPositionData',
  // 'User',
  // 'RoomData',
  // 'CharacterData',
  // 'UserData',
  // 'C2SRegisterRequest',
  // 'S2CRegisterResponse',
  // 'C2SLoginRequest',
  // 'S2CLoginResponse',
  // 'S2CMonsterAwakeNotification',
  // 'S2CMonsterMoveNotification',
  // 'C2SPlayerAttackRequest',
  // 'S2CPlayerAttackNotification',
  // 'S2CMonsterSpawnNotification',
  // 'S2CMonsterDeathNotification',
  // 'S2CMonsterHpUpdateNotification',
  // 'C2SCreateRoomRequest',
  // 'S2CCreateRoomResponse',
  // 'C2SGetRoomListRequest',
  // 'S2CGetRoomListResponse',
  // 'C2SJoinRoomRequest',
  // 'S2CJoinRoomResponse',
  // 'C2SGamePrepareRequest',
  // 'S2CGamePrepareResponse',
  // 'S2CGamePrepareNotification',
  // 'C2SGameStartRequest',
  // 'S2CGameStartResponse',
  // 'S2CGameStartNotification',
  // 'C2SPositionUpdateRequest',
  // 'S2CPositionUpdateNotification',
  // 'S2CUserUpdateNotification',
  // 'S2CPlayerDeathNotification',
  // 'S2CPlayerHpUpdateNotification',
  // 'C2SEatFoodRequest',
  // 'S2CEatFoodResponse',
  'GamePacket',
];
