export const ATK_PER_LV = 0;
export const PLAYER_MAX_HUNGER = 100;
export const PLAYER_DEFAULT_RANGE = 10; //기본 공격 사거리
export const PLAYER_DEFAULT_ANGLE = 180; //기본 공격 각도
export const PLAYER_MAX_HP = 100;
export const PLAYER_SPEED = 3;
export const VALID_DISTANCE = 10; //얼만큼이 적당하지..?
export const PLAYER_HUNGER_PERIOD = 2000; // 허기 감소 주기 : 2초
export const PLAYER_HUNGER_DECREASE_AMOUNT = 1; // 허기 감소 값
export const PLAYER_HP_DECREASE_AMOUNT_BY_HUNGER = 5; // 허기 0 이하일 때 허기 감소 주기 당 체력 감소 값
