export const PACKET_TYPE_BYTE = 2;
export const VERSION_LENGTH_BYTE = 1;
export const PAYLOAD_LENGTH_BYTE = 4;

export const PACKET_TYPE = {
    // 유저 회원가입,로그인
    REGISTER_REQUEST: 1001,
    REGISTER_RESPONSE: 1002,
    LOGIN_REQUEST: 1003,
    LOGIN_RESPONSE: 1004,

    // 방 생성,참가
    CREATE_ROOM_REQUEST: 2001,
    CREATE_ROOM_RESPONSE: 2002,
    JOIN_ROOM_REQUEST: 2003,
    JOIN_ROOM_RESPONSE: 2004,
    GET_ROOM_LIST_REQUEST: 2005,
    GET_ROOM_LIST_RESPONSE: 2006,

    // 게임 시작
    PREPARE_GAME_REQUEST: 3001,
    PREPARE_GAME_RESPONSE: 3002,
    PREPARE_GAME_NOTIFICATION: 3003,
    START_GAME_REQUEST: 3004,
    START_GAME_RESPONSE: 3005,
    START_GAME_NOTIFICATION: 3006,

    // 플레이어 
    PLAYER_UPDATE_POSITION_REQUEST: 4001,
    PLAYER_UPDATE_POSITION_NOTIFICATION: 4002,
    PLAYER_UPDATE_HP_NOTIFICATION: 4003,
    PLAYER_ATTACK_REQUEST: 4004,
    PLAYER_ATTACK_NOTIFICATION: 4005,
    PLAYER_DEAD_NOTIFICATION: 4006,
    USER_UPDATE_NOTIFICATION: 4040,

    // 몬스터
    MONSTER_SPAWN_NOTIFICATION: 5001,
    MONSTER_AWAKE_NOTIFICATION: 5002,
    MONSTER_MOVE_NOTIFICATION: 5003,
    MONSTER_DEATH_NOTIFICATION: 5004,
    MONSTER_HP_UPDATE_NOTIFICATION: 5005,
}